In [2]:
import numpy as np

In [3]:
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [4]:
C = np.dot(A, B)

In [5]:
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [6]:
print(C.max())

47
